local DATA_FILE = "Data.TXT"
local OUT_FILE  = "index.html"

local function read_all(file)
    local f = io.open(file, "r")
    if not f then return nil end
    local content = f:read("*all")
    f:close()
    return content
end

local raw_data = read_all(DATA_FILE)
if not raw_data then
    print("Error: Could not find " .. DATA_FILE)
    os.exit(1)
end

local entries = {}
for meta_part, content_part in raw_data:gmatch("([%w%s%p]-)\n%-%-%-\n(.-)\n%-%-%-") do
    local entry = { content = content_part:match("^%s*(.-)%s*$") }
    for line in meta_part:gmatch("[^\r\n]+") do
        local k, v = line:match("^(%w+)%s*:%s*(.+)$")
        if k then entry[k] = v end
    end
    table.insert(entries, entry)
end

local head = [[<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>My Timeline</title>
<style>
    @font-face {
        font-family: 'ChillBitmap_16px';
        src: url('ChillBitmap_16px.ttf');
    }
    body {
        font-family: 'ChillBitmap_16px', monospace;
        max-width: 700px;
        margin: 2em auto;
        padding: 0 1em;
        line-height: 1.5;
        background: #fff;
        color: #000;
        -webkit-font-smoothing: none;
    }
    h1 {
        font-size: 1.5em;
        border-bottom: 2px solid #000;
        padding-bottom: 10px;
        text-transform: uppercase;
    }
    .c {
        margin-bottom: 2em;
        border-left: 4px solid #000;
        padding-left: 1.2em;
    }
    .m {
        font-weight: bold;
        margin-bottom: 0.5em;
        background: #eee;
        display: inline-block;
        padding: 2px 8px;
    }
    .d {
        font-weight: normal;
        font-size: 0.85em;
        color: #666;
        margin-left: 10px;
    }
    .p {
        white-space: pre-wrap;
        word-wrap: break-word;
        margin-top: 0.5em;
    }
    footer {
        margin-top: 5em;
        font-size: 0.8em;
        border-top: 1px dotted #000;
        padding-top: 1em;
        color: #999;
    }
</style>
</head>
<body>
<h1>My Timeline</h1>
]]

local foot = string.format([[
<footer>generated by <a href="https://github.com/cynaptic/lua-logbook">lua-logbook</a> @ %s</footer>
</body>
</html>]], os.date("%Y-%m-%d %H:%M"))

local out = io.open(OUT_FILE, "w")
out:write(head)

for i = #entries, 1, -1 do
    local e = entries[i]
    out:write('<div class="c">\n')
    out:write(string.format('  <div class="m">%s <span class="d">[%s]</span></div>\n', e.name or "Anon", e.date or "N/A"))
    out:write(string.format('  <div class="p">%s</div>\n', e.content))
    out:write('</div>\n')
end

out:write(foot)
out:close()

print("Success: Generated " .. OUT_FILE .. " with " .. #entries .. " entries.")
